version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: "web.manager.place"
    ports:
      - "8801:80"
    volumes:
      - ./config/services/web.conf:/etc/nginx/nginx.conf
      - ./logs/web:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - php-fpm
      - console
      - crm.auth
      - crm.bank
      - crm.black_list
      - crm.employee
      - crm.role
      - crm.country
      - crm.city
      - crm.region
      - crm.developer
      - crm.marketplace
      - crm.offer
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.2

  crm.employee:
    image: nginx:latest
    container_name: "employee.manager.place"
    working_dir: /var/www/employee
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/employee:/var/www/employee
      - ./config/services/api.v1.crm.employee.conf:/etc/nginx/nginx.conf
      - ./logs/services/employee:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.3

  crm.role:
    image: nginx:latest
    container_name: "role.manager.place"
    working_dir: /var/www/role
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/role:/var/www/role
      - ./config/services/api.v1.crm.role.conf:/etc/nginx/nginx.conf
      - ./logs/services/role:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.4

  crm.auth:
    image: nginx:latest
    working_dir: /var/www/auth
    container_name: "auth.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/auth:/var/www/auth
      - ./config/services/api.v1.crm.auth.conf:/etc/nginx/nginx.conf
      - ./logs/services/auth:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.5

  crm.country:
    image: nginx:latest
    working_dir: /var/www/country
    container_name: "country.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/country:/var/www/country
      - ./config/services/api.v1.crm.country.conf:/etc/nginx/nginx.conf
      - ./logs/services/country:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.6

  crm.region:
    image: nginx:latest
    working_dir: /var/www/region
    container_name: "region.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/region:/var/www/region
      - ./config/services/api.v1.crm.region.conf:/etc/nginx/nginx.conf
      - ./logs/services/region:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.7

  crm.city:
    image: nginx:latest
    working_dir: /var/www/city
    container_name: "city.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/city:/var/www/city
      - ./config/services/api.v1.crm.city.conf:/etc/nginx/nginx.conf
      - ./logs/services/city:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.8

  crm.marketplace:
    image: nginx:latest
    working_dir: /var/www/marketplace
    container_name: "marketplace.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/marketplace:/var/www/marketplace
      - ./config/services/api.v1.crm.marketplace.conf:/etc/nginx/nginx.conf
      - ./logs/services/marketplace:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.9

  crm.developer:
    image: nginx:latest
    working_dir: /var/www/developer
    container_name: "developer.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/developer:/var/www/developer
      - ./config/services/api.v1.crm.developer.conf:/etc/nginx/nginx.conf
      - ./logs/services/developer:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.10

  crm.bank:
    image: nginx:latest
    working_dir: /var/www/bank
    container_name: "bank.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/bank:/var/www/bank
      - ./config/services/api.v1.crm.bank.conf:/etc/nginx/nginx.conf
      - ./logs/services/bank:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.11

  crm.black_list:
    image: nginx:latest
    working_dir: /var/www/black_list
    container_name: "black_list.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/black_list:/var/www/black_list
      - ./config/services/api.v1.crm.black_list.conf:/etc/nginx/nginx.conf
      - ./logs/services/black_list:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.12

  crm.offer:
    image: nginx:latest
    working_dir: /var/www/offer
    container_name: "offer.manager.place"
    links:
      - php-fpm
    volumes:
      - ./services/api/v1/crm/offer:/var/www/offer
      - ./config/services/api.v1.crm.offer.conf:/etc/nginx/nginx.conf
      - ./logs/services/offer:/var/logs/nginx
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - websocket-server
    networks:
      net.manager.place:
        ipv4_address: 172.25.0.13

  redis:
    image: redis:6.2-alpine
    container_name: "redis.manager.place"
    environment:
      TZ: ${TIME_ZONE}
    ports:
      - "9900:${REDIS_PORT}"
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - "./data/db/redis:/data:rw"
    restart: always
    networks:
      net.manager.place:
        ipv4_address: ${REDIS_HOST_IP}

  postgres:
    image: postgres:16
    container_name: "db.manager.place"
    environment:
      TZ: ${TIME_ZONE}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./data/db/postgresql:/var/lib/postgresql/data/pgdata:rw
        - ./logs/services/postgres:/var/log/postgresql:rw
        - ./data/db/dump/postgresql:/dump:rw
        - ./scripts/postgres/create_dump.sh:/usr/bin/create_dump
        - ./scripts/postgres/load_dump.sh:/usr/bin/load_dump
    ports:
        - "9901:${DB_PORT}"
    restart: always
    networks:
      net.manager.place:
        ipv4_address: ${DB_HOST_IP}

  php-fpm:
    build:
      context: docker/php
    container_name: "php-fpm.manager.place"
    volumes:
      - ./src/crm:/var/www/crm/:rw
      - ./services/console:/var/www/console:rw
      - ./services/api/v1/crm/bank:/var/www/bank:rw
      - ./services/api/v1/crm/black_list:/var/www/black_list:rw
      - ./services/api/v1/crm/employee:/var/www/employee:rw
      - ./services/api/v1/crm/developer:/var/www/developer:rw
      - ./services/api/v1/crm/marketplace:/var/www/marketplace:rw
      - ./services/api/v1/crm/country:/var/www/country:rw
      - ./services/api/v1/crm/region:/var/www/region:rw
      - ./services/api/v1/crm/city:/var/www/city:rw
      - ./services/api/v1/crm/auth:/var/www/auth:rw
      - ./services/api/v1/crm/role:/var/www/role:rw
      - ./services/api/v1/crm/offer:/var/www/offer:rw
    restart: always
    environment:
      # PHP
      TZ: ${TIME_ZONE}
      TIME_ZONE: ${TIME_ZONE}
      # DATABASE
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST_IP}
      # REDIS
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST_IP}
      # WEBSOCKET
      WEBSOCKET_LOCAL_HOST: ${WS_LOCAL_HOST}
      WEBSOCKET_LOCAL_PORT: ${WS_LOCAL_PORT}
    links:
      - redis
      - postgres
    depends_on:
      - websocket-server
      - redis
      - postgres
    networks:
      net.manager.place:
        ipv4_address: ${PHP_FPM_HOST_IP}

  console:
    build:
      context: docker/php
    container_name: "console.manager.place"
    volumes:
      - ./src/crm:/var/www/crm/:rw
      - ./services/console/:/var/www/html/:rw
      - ./logs/services/console:/var/log:rw
      - ./scripts/postgres/create_dump.sh:/usr/bin/create_dump
      - ./scripts/postgres/load_dump.sh:/usr/bin/load_dump
    working_dir: /var/www/html
    environment:
      # PHP
      TZ: ${TIME_ZONE}
      TIME_ZONE: ${TIME_ZONE}
      # DATABASE
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST_IP}
      # REDIS
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST_IP}
      # WEBSOCKET
      WEBSOCKET_LOCAL_HOST: ${WS_LOCAL_HOST}
      WEBSOCKET_LOCAL_PORT: ${WS_LOCAL_PORT}
    restart: always
    links:
      - redis
      - postgres
      - php-fpm
    depends_on:
      - redis
      - postgres
      - php-fpm
      - websocket-server

  websocket-server:
    build:
      context: docker/ws
    container_name: "ws.manager.place"
    environment:
      TZ: ${TIME_ZONE}
    working_dir: /opt/ws
    restart: always
    volumes:
      - ./services/ws/server.js:/opt/ws/server.js:rw
    networks:
      net.manager.place:
        ipv4_address: ${WS_LOCAL_HOST}

networks:
  net.manager.place:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24